packages:
  - apps/*
  - packages/*

allowBuilds:
  "@prisma/engines": true
  "@scarf/scarf": false
  "esbuild@0.28.2": true
  prisma: true

engineStrict: true
saveExact: true
sharedWorkspaceLockfile: true
strictPeerDependencies: true
